// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/result": {
            "get": {
                "description": "Get result",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "result"
                ],
                "operationId": "get-result",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/result.Result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scores": {
            "get": {
                "description": "Get all scores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "operationId": "get-scores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/score.Score"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "result.Result": {
            "type": "object",
            "properties": {
                "fourthPlace": {
                    "$ref": "#/definitions/team.Team"
                },
                "runnerUp": {
                    "$ref": "#/definitions/team.Team"
                },
                "thirdPlace": {
                    "$ref": "#/definitions/team.Team"
                },
                "winner": {
                    "$ref": "#/definitions/team.Team"
                }
            }
        },
        "score.Score": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/result.Result"
                },
                "totalScore": {
                    "type": "integer"
                }
            }
        },
        "team.Team": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Euros Sweepstakes API",
	Description:      "Returns scores for the Euro 2024 sweepstakes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
