basePath: /api/v1
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  result.Result:
    properties:
      fourthPlace:
        $ref: '#/definitions/team.Team'
      runnerUp:
        $ref: '#/definitions/team.Team'
      thirdPlace:
        $ref: '#/definitions/team.Team'
      winner:
        $ref: '#/definitions/team.Team'
    type: object
  score.Score:
    properties:
      name:
        type: string
      result:
        $ref: '#/definitions/result.Result'
      totalScore:
        type: integer
    type: object
  team.Team:
    properties:
      country:
        type: string
    type: object
info:
  contact: {}
  description: Returns scores for the Euro 2024 sweepstakes
  title: Euros Sweepstakes API
  version: 0.1.0
paths:
  /result:
    get:
      description: Get result
      operationId: get-result
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - result
  /scores:
    get:
      description: Get all scores
      operationId: get-scores
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/score.Score'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - scores
swagger: "2.0"
