basePath: /api/v1
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  score.Score:
    properties:
      name:
        type: string
      teams:
        items:
          $ref: '#/definitions/score.Team'
        type: array
      totalScore:
        type: integer
    type: object
  score.Team:
    properties:
      country:
        type: string
      flag:
        type: string
      score:
        type: integer
    type: object
info:
  contact: {}
  description: Returns scores for the Euro 2024 sweepstakes
  title: Euros Sweepstakes API
  version: 0.1.0
paths:
  /scores:
    get:
      description: Get all scores
      operationId: get-scores
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/score.Score'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - scores
swagger: "2.0"
