services:
  redis:
    image: bitnami/redis:7.0
    container_name: redis
    restart: always
    env_file: redis.env
    ports:
      - 6379:6379
    networks:
      - sweepstakes

networks:
  sweepstakes:
    driver: bridge
    name: sweepstakes
